// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

import { ERC20Table, ERC20TableData, ERC20TableTableId } from "./tables/ERC20Table.sol";
import { AllowanceTable, AllowanceTableTableId } from "./tables/AllowanceTable.sol";
