// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

import { ERC20Table, ERC20TableData } from "./tables/ERC20Table.sol";
import { AllowanceTable } from "./tables/AllowanceTable.sol";
