// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

import { MetadataTable, MetadataTableData } from "./MetadataTable.sol";
import { BalanceTable } from "./BalanceTable.sol";
import { AllowanceTable } from "./AllowanceTable.sol";
import { ERC721Table, ERC721TableData } from "./ERC721Table.sol";
