// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

import { Counter } from "./tables/Counter.sol";
import { AllowanceTable } from "./tables/AllowanceTable.sol";
import { BalanceTable } from "./tables/BalanceTable.sol";
import { MetadataTable, MetadataTableData } from "./tables/MetadataTable.sol";
import { ERC721Table, ERC721TableData } from "./tables/ERC721Table.sol";
import { ERC1155ApprovalTable } from "./tables/ERC1155ApprovalTable.sol";
import { ERC1155BalanceTable } from "./tables/ERC1155BalanceTable.sol";
import { ERC1155MetadataTable, ERC1155MetadataTableData } from "./tables/ERC1155MetadataTable.sol";
