// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

interface IERC20TestToken {
  function mint20(uint256 amount) external;

  function burn20(uint256 amount) external;

  function transfer20(address to, uint256 amount) external;

  function place20(uint256 amount, uint256 x, uint256 y) external;

  function location20(uint256 amount) external view returns (uint256 x, uint256 y);
}
