// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

interface IERC1155TestToken {
  function mint1155(uint256 tokenId, uint256 amount) external;

  function burn1155(uint256 tokenId, uint256 amount) external;

  function transfer1155(address to, uint256 tokenId, uint256 amount) external;

  function place1155(uint256 tokenId, uint256 x, uint256 y) external;

  function location1155(uint256 tokenId) external view returns (uint256 x, uint256 y);
}
