// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

interface IERC721TestToken {
  function mint721(uint256 tokenId) external;

  function burn721(uint256 tokenId) external;

  function transfer721(address to, uint256 tokenId) external;

  function place721(uint256 tokenId, uint256 x, uint256 y) external;

  function location721(uint256 tokenId) external view returns (uint256 x, uint256 y);
}
