// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

interface IERC20System {
  function initializeMetadata(uint256 tokenId, address _proxy, string calldata _name, string calldata _symbol) external;

  function name(uint256 tokenId) external view returns (string memory);

  function symbol(uint256 tokenId) external view returns (string memory);

  function decimals() external pure returns (uint8);

  function totalSupply(uint256 tokenId) external view returns (uint256);

  function balanceOf(uint256 tokenId, address account) external view returns (uint256);

  function transfer(uint256 tokenId, address to, uint256 amount) external returns (bool);

  function allowance(uint256 tokenId, address owner, address spender) external view returns (uint256);

  function approve(uint256 tokenId, address spender, uint256 amount) external;

  function transferFrom(uint256 tokenId, address from, address to, uint256 amount) external;

  function increaseAllowance(uint256 tokenId, address spender, uint256 addedValue) external;

  function decreaseAllowance(uint256 tokenId, address spender, uint256 subtractedValue) external returns (bool);
}
