// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

interface IERC20TestTokenSystem {
  function mint(address tokenId, address to, uint256 amount) external;

  function burn(address tokenId, address from, uint256 amount) external;
}
