// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

interface IERC20System {
  function initializeERC20(address tokenId, string calldata _name, string calldata _symbol) external;

  function nameERC20(address tokenId) external view returns (string memory);

  function symbolERC20(address tokenId) external view returns (string memory);

  function totalSupplyERC20(address tokenId) external view returns (uint256);

  function balanceOfERC20(address tokenId, address account) external view returns (uint256);

  function transferERC20(address tokenId, address to, uint256 amount) external;

  function allowanceERC20(address tokenId, address owner, address spender) external view returns (uint256);

  function approveERC20(address tokenId, address spender, uint256 amount) external;

  function transferFromERC20(address tokenId, address from, address to, uint256 amount) external;

  function increaseAllowanceERC20(address tokenId, address spender, uint256 addedValue) external;

  function decreaseAllowanceERC20(address tokenId, address spender, uint256 subtractedValue) external;

  function transferERC20(address tokenId, address from, address to, uint256 amount) external;

  function mintERC20(address tokenId, address account, uint256 amount) external;

  function burnERC20(address tokenId, address account, uint256 amount) external;

  function approveERC20(address tokenId, address owner, address spender, uint256 amount) external;

  function spendAllowanceERC20(address tokenId, address owner, address spender, uint256 amount) external;
}
